# IMPORTING NUMPY

In [1]:
import numpy as np

# BASIC CODES

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
b=np.array([[1.2,3.5,4.6],[1.7,5.6,8.9]])
b

array([[1.2, 3.5, 4.6],
       [1.7, 5.6, 8.9]])

In [5]:
print(b)

[[1.2 3.5 4.6]
 [1.7 5.6 8.9]]


In [6]:
#Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [7]:
#Get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
#Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [9]:
#Get Size
print(a.itemsize)
print(b.itemsize)

4
8


In [10]:
#Get Total Size
print(a.nbytes)
print(b.nbytes)

12
48


# Excessing Specific Location 

In [11]:
a=np.array([[1,2,3,4,5,6,7],[6,7,8,9,10,11,12]],dtype='int32')
print(a)

[[ 1  2  3  4  5  6  7]
 [ 6  7  8  9 10 11 12]]


In [12]:
#Get Specific element [r,c]
a[0,4]

5

In [13]:
#Get Specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
#Get Specific column
a[:,2]

array([3, 8])

In [15]:
#Get start stop step [row,start:stop:step]
a[1, 1:-1:2]

array([ 7,  9, 11])

In [16]:
#Change element
print(a)
a[0,3]=0
print(a)

[[ 1  2  3  4  5  6  7]
 [ 6  7  8  9 10 11 12]]
[[ 1  2  3  0  5  6  7]
 [ 6  7  8  9 10 11 12]]


In [17]:
#Change row and column
a[1,:]=5
a[:,3]=0
print(a)

[[1 2 3 0 5 6 7]
 [5 5 5 0 5 5 5]]


# 3-D Array

In [18]:
d=np.array([[[1,2],[3,5]],[[6,7],[8,9]]])
print(d)

[[[1 2]
  [3 5]]

 [[6 7]
  [8 9]]]


In [19]:
#Get element from position
d[1::]

array([[[6, 7],
        [8, 9]]])

In [20]:
#Replace element
d[1,1,1]=0
d

array([[[1, 2],
        [3, 5]],

       [[6, 7],
        [8, 0]]])

# Types of array

In [21]:
#Zero Metrix
np.zeros((2,2,3),dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [22]:
#Ones Metrix
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [23]:
#Number Metrix
np.full((2,2,2),76)

array([[[76, 76],
        [76, 76]],

       [[76, 76],
        [76, 76]]])

In [24]:
#Metrix like other
np.full(d.shape,34)

array([[[34, 34],
        [34, 34]],

       [[34, 34],
        [34, 34]]])

In [25]:
#Metrix like
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [26]:
#Random Metrix
np.random.rand(3,2,3)

array([[[0.66016005, 0.77309447, 0.77860399],
        [0.64776426, 0.7236367 , 0.73056434]],

       [[0.26941399, 0.07716324, 0.74581386],
        [0.60957503, 0.67256142, 0.55950615]],

       [[0.47931634, 0.68759733, 0.56310967],
        [0.78410101, 0.10701947, 0.7669413 ]]])

In [27]:
#Random Like
np.random.random_sample(d.shape)

array([[[0.09772832, 0.70416029],
        [0.63569318, 0.84045406]],

       [[0.09759663, 0.5530191 ],
        [0.22323259, 0.35462578]]])

In [28]:
#Random Ineger
np.random.randint(0,10,size=(2,3))

array([[9, 3, 4],
       [8, 5, 8]])

In [29]:
#Identity matrix
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
#Repeat Array
arr=np.array([[1,2,3],[4,5,6]])
r=np.repeat(arr,2,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


In [31]:
#Pattern
o=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
o[1:-1,1:-1]=z #o[1:4,1:4]
print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copying Array

In [32]:
a=np.array([1,2,3])
b=a.copy()
print(a)

[1 2 3]


# MATHEMATICS

In [33]:
op=np.array([1,2,3,4,5])
print(a)

[1 2 3]


In [34]:
op+2

array([3, 4, 5, 6, 7])

In [35]:
op-2

array([-1,  0,  1,  2,  3])

In [36]:
op*2

array([ 2,  4,  6,  8, 10])

In [37]:
a/2

array([0.5, 1. , 1.5])

In [38]:
a**2

array([1, 4, 9], dtype=int32)

In [39]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [40]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [41]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654])

# Linear Algebra

In [42]:
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [43]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [44]:
c=np.identity(3)
np.transpose(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# STATISTICS

In [45]:
s=np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(s)

1

In [47]:
np.max(s)

6

In [48]:
np.sum(s,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [49]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape,end="\n\n")
print(a,end="\n\n")

b=a.reshape(3,2)
print(b)

(2, 3)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [50]:
#stacking vertically
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [51]:
#stacking horizontally
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

# Micellaneous

### Load data from file

In [52]:
fd=np.genfromtxt('img_jyp/arrayNpy.txt',delimiter=' ')
fd.astype('int32')

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

### Boolean masking and advanced imdexing

In [53]:
fd < 10

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [54]:
fd[fd<10]

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
np.any(fd<10,axis=1)

array([ True, False, False, False])

In [56]:
((fd > 20) & (fd < 40))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False]])

### indexing with list

In [57]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,4,8]]

array([2, 5, 9])